apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-local-persistent-volume-claim
  labels:
    volume-type: ssd
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: volume-local-storage-class
  selector:
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}