apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: server
    spec:
      containers:
      - image: nginx
        name: nginx
        imagePullPolicy: IfNotPresent
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html/emptyDir/
          name: empty-dir-volume
      volumes:
      - name: empty-dir-volume
        emptyDir: {}
