apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: service-nodeport
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: mendhak/http-https-echo:25
          name: http-echo
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
