apiVersion: v1
kind: Service
metadata:
  name: meu-backend
  namespace: service-nodeport
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 8080
      nodePort: 30280
